version: '3.7'
services:
  mongodb_container:
    image: mongo:5.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  web:
    build: .
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    ports:
      - 5001:5000
    links: 
     - mongodb_container

volumes:
  mongodb_data_container: